### ISSUE TITLE
test checkbox auto statistic

### ISSUE THREAD

**Issue by daiyy2009** [daiyy2009/chrome-extend#1]
layer auto statistic

**Comment by daiyy2009** [comment]
### 自动生成的统计信息： 
共有问题：3个
已经解决问题：1个 
- [ ] <span>1、</span><a href="https://github.com/daiyy2009/chrome-extensions/issues/1#issuecomment-315594899"> des two</a>
- [x] <span>2、</span><a href="https://github.com/daiyy2009/chrome-extensions/issues/1#issuecomment-315598514"> des three</a>
- [ ] <span>3、</span><a href="https://github.com/daiyy2009/chrome-extensions/issues/1#issuecomment-315598524"> des one</a>

**Comment by daiyy2009** [comment]
- [ ] des two
- [ ] des two

**Comment by daiyy2009** [comment]
- [x] des three

**Comment by daiyy2009** [comment]
- [ ] des one
